name: Clandestinos
version: 1.0
author: FoxSGR
main: foxsgr.clandestinos.application.Clandestinos
api-version: 1.14

depend:
  - Vault

softdepend:
  - PlaceholderAPI

commands:
  clan:
    description: Clan command.
    usage: "Use: /clan"
    permission-message: You not have have permission to use this command.
    aliases:
      - clans
  .:
    description: Clan chat command.
    usage: "Use: /. [text]"
    permission-message: You not have have permission to use this command.
    aliases:
      - clanchat

permissions:
  clandestinos.*:
    description: Allows every Clandestinos command.
    children:
      clandestinos.reload:
        default: op
      clandestinos.create:
        default: true
      clandestinos.invite:
        default: true
      clandestinos.uninvite:
        default: true
      clandestinos.leave:
        default: true
      clandestinos.join:
        default: true
      clandestinos.disband:
        default: true
      clandestinos.kick:
        default: true
      clandestinos.modtag:
        default: true
      clandestinos.clanchat:
        default: true
      clandestinos.spy:
        default: op
      clandestinos.enemy:
        default: true
      clandestinos.unenemy:
        default: true
      clandestinos.makeleader:
        default: true
      clandestinos.makemember:
        default: true
      clandestinos.debug:
        default: op
      clandestinos.list:
        default: true
