name: Clandestinos
version: 1.0
author: FoxSGR
main: foxsgr.clandestinos.application.Clandestinos
api-version: 1.14

depend:
  - Vault

softdepend:
  - PlaceholderAPI

commands:
  clan:
    description: Clan command.
    usage: "Use: /clan"
    permission-message: You not have have permission to use this command.
    aliases:
      - clans
  .:
    description: Clan chat command.
    usage: "Use: /. [text]"
    permission-message: You not have have permission to use this command.
    aliases:
      - clanchat

permissions:
  clandestinos.*:
    description: Allows every Clandestinos command.
    children:
      clandestinos.reload: false
      clandestinos.create: true
      clandestinos.invite: true
      clandestinos.uninvite: true
      clandestinos.leave: true
      clandestinos.join: true
      clandestinos.disband: true
      clandestinos.kick: true
      clandestinos.modtag: true
      clandestinos.clanchat: true
      clandestinos.spy: false
      clandestinos.enemy: true
      clandestinos.unenemy: true
      clandestinos.makeleader: true
      clandestinos.makemember: true
