
DROP DATABASE clandestinos;
CREATE DATABASE clandestinos;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS clan;
DROP TABLE IF EXISTS clan_member;
DROP TABLE IF EXISTS clan_leader;
DROP TABLE IF EXISTS clan_enemy;
DROP TABLE IF EXISTS invite;
DROP TABLE IF EXISTS neutrality_request;
DROP TABLE IF EXISTS player;

SET FOREIGN_KEY_CHECKS = 1;
